version: '3.8'

services:
  db:
    image: mongo:6.0
    container_name: f1mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: f1hub

volumes:
  mongo_data:
