name: F1-FuelHub - Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ########################################################
  ### Unit Test ##########################################
  ########################################################
  unit-test:
    name: Run Unit Tests on ${{ matrix.os }}
    # Use a strategy matrix to create a job for each OS
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # The runs-on key now references the matrix variable
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use actions/setup-node to install Node.js on each OS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          # Optional: Use caching to speed up dependency installation
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
