name: F1-FuelHub - Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ########################################################
  ### Unit Test ##########################################
  ########################################################
  unit-test:
    name: Run Unit Tests
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    container:
      image: node:22-alpine
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
